language: php
php:
    - 5.4
    - 5.5

before_script:
    - ./travis.sh
    - chmod 777 src/Mapado/SimstringBundle/Tests/Database/
    - composer install --dev

script: bin/atoum -f src/Mapado/SimstringBundle/Tests/Units/Database/SimstringClient.php -bf vendor/autoload.php
